# Generated by Django 4.0.4 on 2022-05-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('mail', models.EmailField(max_length=40, verbose_name='Email')),
                ('post_text', models.TextField(max_length=2000, verbose_name='Your text')),
                ('time_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('status', models.CharField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=30, verbose_name='status')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
                'db_table': 'guest_book',
            },
        ),
    ]
